### ISSUE TITLE
Unable to start video on Android Oreo

### ISSUE THREAD

**Issue by AdamMc331** [JakeWharton/Telecine#163]
I just installed Android Oreo, and when I went to use the app to record something, I couldn't click the start button as it appears the actually be behind the status bar. When I tap on it, all it does is start to show the notification controller. See attached screenshot.

![telecine](https://user-images.githubusercontent.com/9515997/29757958-aad0ab32-8b7d-11e7-9b6f-efe24fe36e63.png)

**Comment by JakeWharton** [comment]
Dupe of #149. Haven't had time to get to this yet, sorry.

**Comment by AdamMc331** [comment]
Whoops sorry for dupe. I looked but must have missed it. It's late.
