### ISSUE TITLE
Post to XDA/XDA Labs

### ISSUE THREAD

**Issue by Madis0** [JakeWharton/Telecine#169]
Similar request to #148, but since you can't do it, why not consider posting a topic to [XDA Forums](https://forum.xda-developers.com/android/apps-games) and/or a listing to the [XDA Labs](https://labs.xda-developers.com) app store. 

The main reason for this is that this app was really hard to find from Play Store, and more recognition for open-source apps is always good 😉

**Comment by JakeWharton** [comment]
I have no plans on posting elsewhere, sorry. I don't want to maintain multiple listings on multiple stores.
