### ISSUE TITLE
Limit MediaRecorder size

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/Telecine#17]
Some devices can only record up to 1080p. See https://github.com/JakeWharton/Telecine/pull/15.

**Comment by monxalo** [comment]
To summarize:
* `MediaRecorder`uses resolution from the camera instead of the screen (probably).
* `CamcorderProfile` can be used to fetch the device's maximum quality (`QUALITY_HIGH`).

**Comment by monxalo** [comment]
See a possible solution with #19.
