### ISSUE TITLE
Telecine refuse to stop recording when lunched

### ISSUE THREAD

**Issue by idimummy** [JakeWharton/Telecine#174]
#### Expected behavior
App should record screen activities, store the recorded activity, and user should be able to stop the recording when they are done.

#### Actual behavior
When the application is lunched to start recording the app only stops when it want to stop recording, It sometimes freezes the screen and makes it difficult to navigate the screen.

#### How to reproduce
Download Telecine from play store here, launch it the app, try to stop the recording.

•	Operating system: Android Version 7.0  
•	Device used: Tecno Boom J8
•	App Version: 1.6.2

#### Recording Of The Bug
https://youtu.be/D1ibwCpvRtg
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kennykajo/telecine-refuse-to-stop-recording-when-lunched">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JakeWharton** [comment]
In that video, AZ Screen Recorder is using the media projection APIs which prevents Telecine from launching. This is evidenced by the fact that the overlay for Telecine never displays and as a result it never actually starts recording.

**Comment by Coffeemaniac** [comment]
I was able to fix this bug by going to permission setting and enabling "show pop up window" option. Maybe, you forgot to ask for "DRAW OVER OTHER APPS" permission.
