### ISSUE TITLE
"Telecine" is a Brazilian trade mark

### ISSUE THREAD

**Issue by geovanisouza92** [JakeWharton/Telecine#18]
Just for information: [Telecine](http://telecine.globo.com/) is a brazilian entertainement trademark from Globo's news corporation. This could start some troubles/misunderstands in future. :smile:

**Comment by JakeWharton** [comment]
Ugh. I don't really expect this app to blow up and get hundreds of millions of installs or anything. Thanks for letting me know, i'm going to look the other way for now... :eyes: !
