### ISSUE TITLE
Can't press the buttons on the overlay

### ISSUE THREAD

**Issue by ShaunDreclin** [JakeWharton/Telecine#180]
They seem to show up under the system clock, and if I tap them it just pulls down the notification menu

![screenshot](https://user-images.githubusercontent.com/5851433/39676883-c5c2d05e-513f-11e8-8d07-392082bc3712.jpg)

**Comment by JakeWharton** [comment]
Dupe of #149. Unfortunate change in the OS.

**Comment by ShaunDreclin** [comment]
Oh yikes that issue is over a year old, is a fix not coming?
