### ISSUE TITLE
Wrong VirtualDisplay size leading to letter box effect

### ISSUE THREAD

**Issue by SimonMarquis** [JakeWharton/Telecine#22]
[These lines](https://github.com/JakeWharton/Telecine/blob/04811c597926939af46db3b97625f550bdd5a1e2/telecine/src/main/java/com/jakewharton/telecine/RecordingSession.java#L159) of code are computing the wrong video size:

```java
    DisplayMetrics displayMetrics = context.getResources().getDisplayMetrics();
    int displayHeight = displayMetrics.heightPixels * sizePercentage / 100;
    int displayWidth = displayMetrics.widthPixels * sizePercentage / 100;
```

On a Nexus 6, the screen resolution is 1440x2560.
But, this `DisplayMetrics` will contain a size of 1440x2392.
This corresponds to the screen resolution, without the navigation bar.
Therefore, you'll end up with a small (but noticable) letter box effect. :disappointed:  

The solution would be to use the WindowManager service and the getRealMetrics method: 
```
WindowManager wm = (WindowManager) context.getSystemService(WINDOW_SERVICE);
Display display = wm.getDefaultDisplay();
DisplayMetrics metrics = new DisplayMetrics();
display.getRealMetrics(metrics);
```

:smiley:

**Comment by JakeWharton** [comment]
Thanks. Will adjust along with #21.
