### ISSUE TITLE
Call startForeground() in TelecineService.onStartCommand()

### ISSUE THREAD

**Issue by techehcet** [JakeWharton/Telecine#33]
On my Nexus 5, I've noticed Telecine being randomly killed (during recording) by the system. Calling startForeground() should go a long way to preventing this, I think.

**Comment by JakeWharton** [comment]
Doesn't that require a notification?

**Comment by techehcet** [comment]
Yes, but you can make it min priority so there is no status bar icon.  Surely better than the app crashing midway through a recording. Maybe make it optional for those who want to keep their notification drawer clean.

**Comment by JakeWharton** [comment]
Seems reasonable.

**Comment by techehcet** [comment]
Thanks very much for this!  Please consider having the notification by default.
