### ISSUE TITLE
Intent-based API library for 3rd party control of recording.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/Telecine#4]

**Comment by NightlyNexus** [comment]
What would this look like?

My fist thought would be start a Telecine task Activity that accepts some configuration options in the extras and that results back telling the calling Activity if the recording started or not.

Then, have a broadcast send that has the Uri as an extra when the recording is completed.

What are your thoughts?

**Comment by JakeWharton** [comment]
Yep. Pretty much exactly what I thought as well.

**Comment by JakeWharton** [comment]
Not doing this.
