### ISSUE TITLE
Makes System UI to crash on Android 5.1

### ISSUE THREAD

**Issue by lynfogeek** [JakeWharton/Telecine#47]
Since I updated my Nexus 5 to Android 5.1 the app crashes the "System UI" app when I click on the button 'launch overlay'.

Most of the time, Telecine will be killed by the system (probably lacking some RAM to restart the System UI processes) and it is impossible to do any screen cast.

**Comment by JakeWharton** [comment]
This is an android bug (http://b.android.com/159196) and it is fixed in Android 5.1.1. Sadly that version has not rolled out to all of the devices which have 5.1 yet (including mine as well :cry:).
