### ISSUE TITLE
Show touches while recording

### ISSUE THREAD

**Issue by monxalo** [JakeWharton/Telecine#48]
Enable developer settings 'Show touches' options while recording. 

Even though with Lollipop we have touch hints for visual feedback (ripples), there are still some missing like swipe and multitouch gestures.

**Comment by monxalo** [comment]
See #40 for a possible implementation.

**Comment by JakeWharton** [comment]
d1ac7ea6c4e7cd4a30df9a07e72bbb9e2355b73e
