### ISSUE TITLE
Add option to crop video (for example, remove Navigation bar)

### ISSUE THREAD

**Issue by marcardar** [JakeWharton/Telecine#58]
The navigation bar is often unnecessary to include in the recording - indeed, some devices don't have an on screen nav bar, so you wouldn't see it anyway.

It would be really good if this could be auto-cropped from the final video (with an appropriate setting to control this).  I had a quick play with various height parameters in the code, but that only made the whole size smaller.  So, I'm not sure how this can be done, or whether it can be done at all.

The alternative is to crop the video post-production which is obviously cumbersome. Indeed, I'm yet to find a decent tool on OS X, to do this well.

**Comment by JakeWharton** [comment]
This is a great idea. Going to copy what you said over to #42 and close this issue since they're about the same thing.
