### ISSUE TITLE
Option to trigger demo mode on M+

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/Telecine#59]
If Google doesn't screw me and close down permission on final.

https://newcircle.com/s/post/1745/2015/07/10/tweaking-system-ui-tuner

**Comment by NightlyNexus** [comment]
https://gist.github.com/NightlyNexus/106c068e6f80f0151698
may be helpful; it's just copypasta from devunwired's post.

**Comment by JakeWharton** [comment]
GOOGLE CRUSHED MY DREAMS IN MP3. Needs a system-signed permission.

**Comment by NightlyNexus** [comment]
@JakeWharton Would you consider a PR that adds a toggle for Demo Mode (like Show Touches)? The toggle could show up iff the system permission is granted or the device is rooted.

**Comment by JakeWharton** [comment]
Yes!

**Comment by NightlyNexus** [comment]
For future travelers: https://github.com/JakeWharton/Telecine/pull/144
