### ISSUE TITLE
Add design support library, FAB to start recording

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/Telecine#60]
FABulous.

**Comment by jaredsburrows** [comment]
+1

**Comment by quentin41500** [comment]
@JakeWharton Would you just hide the fab button when started and click the hidden fab button to stop the recording ? There is a high chance that this part of the app is used compare to the top right corner. I like having a fab button for starting the video, but we should probably find a better to stop the video.

**Comment by JakeWharton** [comment]
The FAB would launch the overlay whose behavior would stay the same.

**Comment by quentin41500** [comment]
Any preferable icon you want to use for that ? Otherwise i'm just gonna do it using the launch icon from Google

**Comment by monxalo** [comment]
I think one of Google's [Material Design icon pack](https://design.google.com/icons/#ic_play_circle_filled) should suffice.

**Comment by JakeWharton** [comment]
490bfa4a22d2828d58cf965fc31480f6ca73975b
