### ISSUE TITLE
Use share chooser with share notification action

### ISSUE THREAD

**Issue by NightlyNexus** [JakeWharton/Telecine#66]
Minor thing, but it is not ideal that the share action allows for a default application.
Perhaps get the PendingIntent for a BroadcastReceiver and then show the share Intent chooser/picker in the BR.

**Comment by JakeWharton** [comment]
Can we just call [`createChooser`][1] and bundle that in the `PendingIntent`?

 [1]: https://developer.android.com/intl/zh-CN/reference/android/content/Intent.html#createChooser(android.content.Intent, java.lang.CharSequence)
