### ISSUE TITLE
Google Play listing missing link to GitHub repo

### ISSUE THREAD

**Issue by NightlyNexus** [JakeWharton/Telecine#82]
Google Play description:
"This app is open source! Contribute by following the website link below."
Looks like the link didn't get pasted. :)
Sorry, I saw this a few months ago and then forgot about it until tonight. @JakeWharton

**Comment by JakeWharton** [comment]
I believe it's the website link, which is what that was referring to.

**Comment by NightlyNexus** [comment]
Aaaaah, yep; I didn't think about that. Thanks, :+1:
