### ISSUE TITLE
Disable "show pointer touches" even when recording crashes.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/Telecine#91]
Otherwise people are stuck in this mode and they potentially don't even have developer options enabled.

**Comment by monxalo** [comment]
There is a [`setOnErrorListener(android.media.MediaPlayer.OnErrorListener)`](http://developer.android.com/reference/android/media/MediaPlayer.html#setOnErrorListener(android.media.MediaPlayer.OnErrorListener)) although i'm not sure if this is called when the player crashes.
