### ISSUE TITLE
Remove statusbar cast icon when recording

### ISSUE THREAD

**Issue by monxalo** [JakeWharton/Telecine#93]
This is already possible using the System UI Tuner but maybe it can be done programmatically.

**Comment by JakeWharton** [comment]
There's no API for this that I've found, and providing one would be _hugely_ risky on Android's side since it would allow silently recording the screen without any visual indication.

**Comment by monxalo** [comment]
Yeah, agreed. The fact of the AOSP not including the UI Tuner seems to backup those obvious reasons.

**Comment by JakeWharton** [comment]
Looked a bit more, there's no way to do this at present.

**Comment by NightlyNexus** [comment]
For future travelers: https://github.com/JakeWharton/Telecine/pull/144
